### PR TITLE
Updated configuration to use .cfg file and ConfigManager.

### LINKED ISSUE #3: Configuration in Python files?
Most people who will use this plugin are not going to be programmers.  They aren't really going to fare well trying to change configurations the way you currently have it setup.  I would suggest creating a .cfg file with [ConfigManager](https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/config/manager.py#L49) or an .ini file with ConfigObj, as these are much easier to understand and are fairly standard already in Source-engine configurations.

The biggest advantage of using  [ConfigManager](https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/config/manager.py#L49) is that all configuration values are then assigned to a ConVar.  This allows server operators/admins to change those values on the fly and even able to use map-based values.

### PR DESCRIPTION
**Pull request by satoon101**
Added functionality to fix #3.

### CODE REVIEW

**Comment by satoon101** [comment]
As a note, using translations for cfg files uses the server's language setting in the core_settings.ini file if the language is supported.

**Comment by Mahi** [comment]
I'm probably busy for today, but I'll test this asap! Thank you very much satoon, this looks awesome.

**Comment by satoon101** [comment]
No problem, take your time.  I did just fix all merge conflicts with the newest master.  I should also note that a Source.Python update broke the menus of WC:GO, but this pull request fixes those, as well.

**Comment by Predz** [comment]
Thanks for updating your branch with the latest master. I will get to testing it in a bit, am just trying to find all possible bugs after the translations update. I have changed the menus/heroes.py slightly to fix a bug, so hopefully didn't cause conflicts again :worried:

**Comment by Predz** [comment]
My internet has gone down for the next few days and I was going to accept the pull after I had changed 1 issue. In the wcgo.py you need to correct the _init_player function to use the new cfg too. Am on phone atm so can't really do it sorry. Would you mind changing it please? Thanks again Satoon. :)

**Comment by satoon101** [comment]
Not sure how I missed that one.  That should be fixed now.

**Pull request merged**
