### PR TITLE
Added translations capability.

### PR DESCRIPTION
**Pull request by satoon101**
Plugin can now get the proper translation for each player based on their language.

Also added a PluginInfo instance to store plugin information.

### CODE REVIEW

**Comment by Mahi** [comment]
What would you suggest about the `chat_message` and `hint_message`'s string formatting, should we stick with the current approach or use the tokens provided by your translations system? Thank you very much for this, I will merge after some testing and experimenting.

**Comment by satoon101** [comment]
This currently doesn't work, unfortunately.  Sorry, should have tested prior to posting.  I am working on changes right now to get it to.  The simplest way to get it to work would be to use the tokens method of our translation system.  However, it might be worth exploring the option of enhancing our translation system to allow for the .format() method as you are currently using.

**Comment by Mahi** [comment]
I am fine with using your token system, as long as we can combine it into our `chat_message` and `hint_message` functions to support backwards compability (in the Python code, not in the translation strings themselves). Will you do all of that or shall I take a look at it?

**Comment by satoon101** [comment]
I have been working on both already.  I will update this pull request when I am finished.

**Comment by Mahi** [comment]
Alright, thank you very much satoon!

**Comment by satoon101** [comment]
Ok, this should all work if my proposed change to TranslationStrings is adopted.  If not, I will update accordingly.

I did end up having to put the prefix in the chat message translations themselves instead of that being a part of the configuration.  That can be changed, if you want.  The easiest way would be to add a {prefix} keyword to each message, then use the configuration value to fill it in.

**Comment by satoon101** [comment]
Ok, the TranslationStrings change has been accepted and committed, so this should all work fine.
https://github.com/Source-Python-Dev-Team/Source.Python/commit/3b497bff2aeae6f564574b2f8f0f56482a471a41

**Comment by Predz** [comment]
I was testing keywords in the send method of messages the other day, and they never seem to be formatted in. Even using your branch it isn't working. Something we are doing wrong?

**Comment by satoon101** [comment]
It works fine for my testing with the current version of this request.

**Comment by Mahi** [comment]
> I did end up having to put the prefix in the chat message translations themselves instead of that being a part of the configuration. That can be changed, if you want. The easiest way would be to add a {prefix} keyword to each message, then use the configuration value to fill it in.

After a short discussion with @Predz about this, we ended up agreeing that the way you did it is actually better, people might end up wanting different prefixes for different messages. So no need for a configurable prefix.

> Ok, the TranslationStrings change has been accepted and committed, so this should all work fine.
Source-Python-Dev-Team/Source.Python@3b497bf

Seems to work, thank you very much, we appreciate the help!

**Pull request merged**
